In [4]:
m=int(input())
if m % 2==0:
    print("Even")
else :
    print("Odd")

Even


In [7]:
a=int(input())
b=int(input())
c=int(input())
if a>b and a>c:
    print(a," is the greatest")
elif b>a and b>c:
    print(b," is the greatest")
else :
    print(c," is the greatest")

3  is the greatest


In [8]:
a=int(input())
b=int(input())
c=int(input())
print(a+b+c)

6


In [14]:
a=int(input())
flag=True;
for i in range (2,a):
    if a%i==0:
        print("Not prime")
        flag=False
        break
if flag==True:
    print("Prime")
    

Prime


In [15]:
def square(n):
    return n*n
n=int(input())
s=square(n)
print(s)

25


In [17]:
import numpy as np
n=np.array([1,2,3,4,5])
print(n)

[1 2 3 4 5]


In [19]:
import numpy as np
n= np.array(23)
print(n.ndim)

0


In [20]:
n=np.zeros([3,4])
print(n)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
n=np.array([1,2,3,4,5])
print(n[2:5])

[3 4 5]


In [25]:
n=np.array([1,2,3,4,5,6])
n=n.reshape(2,3)
print(n)

[[1 2 3]
 [4 5 6]]


In [30]:
n=np.array([[1,2,3],[4,5,6]])
for i in n:
    print(i)

[1 2 3]
[4 5 6]
